<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Regression &amp; Interpretability Challenge</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-d6a003b94517c951b2d65075d42fb01b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="index_files/libs/quarto-diagram/mermaid.min.js"></script>
<script src="index_files/libs/quarto-diagram/mermaid-init.js"></script>
<link href="index_files/libs/quarto-diagram/mermaid.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Regression &amp; Interpretability Challenge</h1>
<p class="subtitle lead">Don’t Trust Linear Models - The Perils of Non-Linearity</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<!-- # 🗑️ Regression Challenge - Linear Model Interpretability -->
<!-- ## Introduction - to the challenge -->
<section id="introduction-to-the-challenge" class="level2">
<h2 class="anchored" data-anchor-id="introduction-to-the-challenge"><span style="color:brown; font-style:italic;">Introduction – to the challenge</span></h2>
<p>This challenge investigates how linear regression can give misleading coefficients when its core assumption of linearity is violated. We begin with a setting where the true data‑generating process for anxiety is:</p>
<p><span class="math display">\[
\text{Anxiety} = \beta_0 + \beta_1 \cdot \text{Stress} + \beta_2 \cdot \text{Time} + \varepsilon
\]</span></p>
<p>with known coefficients:</p>
<p><span class="math display">\[
\beta_0 = 0, \qquad
\beta_1 = 1, \qquad
\beta_2 = 0.1
\]</span></p>
<p>so the true relationship simplifies to:</p>
<p><span class="math display">\[
\text{Anxiety} = \text{Stress} + 0.1 \cdot \text{Time} + \varepsilon
\]</span></p>
<p>However, researchers typically do <strong>not</strong> observe true physiological Stress. Instead, they observe a survey‑based proxy:</p>
<p><span class="math display">\[
\text{StressSurvey} = g(\text{Stress}) + \nu
\]</span></p>
<p>where ( g() ) is <strong>non‑linear</strong> and ( ) represents measurement noise.</p>
<p>When StressSurvey replaces Stress inside a linear regression model,</p>
<p><span class="math display">\[
\text{Anxiety} = \alpha_0 + \alpha_1 \cdot \text{StressSurvey} + \alpha_2 \cdot \text{Time} + u,
\]</span></p>
<p>the model becomes mis‑specified. As a result, the estimated coefficients may become biased, distorted in magnitude, or even flip signs—even when the regression reports a high (R^2) and statistically significant p‑values.</p>
<p>This challenge demonstrates how such failures occur and why linear regression can be dangerously misleading when relationships are non‑linear or when control variables are measured imperfectly.</p>
</section>
<section id="visual-overview-of-the-true-vs-observed-system" class="level2">
<h2 class="anchored" data-anchor-id="visual-overview-of-the-true-vs-observed-system"><span style="color:brown; font-style:italic;">Visual Overview of the True vs Observed System</span></h2>
<div class="columns">
<div class="column" style="width:48%;">
<div class="cell" data-layout-align="default">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode default code-with-copy"><code class="sourceCode default"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>flowchart TD</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>    classDef title fill:#B3D9FF,stroke:#0066FF,color:#003366,font-weight:bold,font-size:14px</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>    classDef node fill:#66B3FF,stroke:#0066FF,stroke-width:2.5px,color:#000033,font-weight:bold</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>    classDef arrow stroke:#0066FF,stroke-width:2.5px</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    subgraph TrueSystem["TRUE CAUSAL SYSTEM"]</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>        class TrueSystem title</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>        style TrueSystem fill:#E6F2FF,stroke:#0066FF,stroke-width:2.5px,color:#003366,padding:10px</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>        S["True Stress&lt;br/&gt;(Cortisol)"]:::node --&gt;|"β₁ = 1"| A["Anxiety"]:::node</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>        T["Time on Social Media"]:::node --&gt;|"β₂ = 0.1"| A</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    end</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
    classDef title fill:#B3D9FF,stroke:#0066FF,color:#003366,font-weight:bold,font-size:14px
    classDef node fill:#66B3FF,stroke:#0066FF,stroke-width:2.5px,color:#000033,font-weight:bold
    classDef arrow stroke:#0066FF,stroke-width:2.5px

    subgraph TrueSystem["TRUE CAUSAL SYSTEM"]
        class TrueSystem title
        style TrueSystem fill:#E6F2FF,stroke:#0066FF,stroke-width:2.5px,color:#003366,padding:10px

        S["True Stress&lt;br/&gt;(Cortisol)"]:::node --&gt;|"β₁ = 1"| A["Anxiety"]:::node
        T["Time on Social Media"]:::node --&gt;|"β₂ = 0.1"| A
    end
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div><div class="column" style="width:4%;">

</div><div class="column" style="width:48%;">
<div class="cell" data-layout-align="default">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode default code-with-copy"><code class="sourceCode default"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>flowchart TD</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    classDef title fill:#FFE6CC,stroke:#FF6600,color:#993300,font-weight:bold,font-size:14px</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    classDef node fill:#FFB366,stroke:#FF6600,stroke-width:2.5px,color:#330000,font-weight:bold</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    classDef arrow stroke:#FF6600,stroke-width:2.5px</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    subgraph ObservedSystem["OBSERVED SYSTEM"]</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>        class ObservedSystem title</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>        style ObservedSystem fill:#FFF4E6,stroke:#FF6600,stroke-width:2.5px,color:#993300,padding:10px</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>        S["True Stress&lt;br/&gt;(Unobserved)"]:::node --&gt;|"Non-linear g(·)&lt;br/&gt;+ noise ν"| SS["StressSurvey&lt;br/&gt;(Proxy)"]:::node</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>        SS --&gt;|"Assumed&lt;br/&gt;Linear"| R["Mis-Specified Regression:&lt;br/&gt;Anxiety = α₀ + α₁·Survey + α₂·Time"]:::node</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>        T["Time on Social Media"]:::node --&gt; R</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    end</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
    classDef title fill:#FFE6CC,stroke:#FF6600,color:#993300,font-weight:bold,font-size:14px
    classDef node fill:#FFB366,stroke:#FF6600,stroke-width:2.5px,color:#330000,font-weight:bold
    classDef arrow stroke:#FF6600,stroke-width:2.5px

    subgraph ObservedSystem["OBSERVED SYSTEM"]
        class ObservedSystem title
        style ObservedSystem fill:#FFF4E6,stroke:#FF6600,stroke-width:2.5px,color:#993300,padding:10px

        S["True Stress&lt;br/&gt;(Unobserved)"]:::node --&gt;|"Non-linear g(·)&lt;br/&gt;+ noise ν"| SS["StressSurvey&lt;br/&gt;(Proxy)"]:::node
        SS --&gt;|"Assumed&lt;br/&gt;Linear"| R["Mis-Specified Regression:&lt;br/&gt;Anxiety = α₀ + α₁·Survey + α₂·Time"]:::node
        T["Time on Social Media"]:::node --&gt; R
    end
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div>
</div>
<p>These diagrams help illustrate how the true linear relationships differ from the incorrectly observed proxy-based model, visually reinforcing the interpretability risks discussed in the introduction.</p>
<!-- ## Challenge Overview

**Your Mission:** Create a comprehensive Quarto document that demonstrates the dangers of trusting linear models when relationships are non-linear, analyzes the interpretability issues that arise, and presents compelling visual evidence of why we need to be skeptical of regression results. Then render the document to HTML and deploy it via GitHub Pages using the starter repository workflow. -->
<!-- ::: {.callout-warning}
## ⚠️ AI Partnership Required

This challenge pushes boundaries intentionally. You'll tackle problems that normally require weeks of study, but with Cursor AI as your partner (and your brain keeping it honest), you can accomplish more than you thought possible.

**The new reality:** The four stages of competence are Ignorance → Awareness → Learning → Mastery. AI lets us produce Mastery-level work while operating primarily in the Awareness stage. I focus on awareness training, you leverage AI for execution, and together we create outputs that used to require years of dedicated study.
::: -->
<!-- ## Problem Violating the Assumption of Linearity🎯

> "We need to stop believing much of the empirical work we've been doing." - Christopher H. Achen

**The Core Problem:** When researchers need to 'control for' variables using linear regression, what happens when the relationships are non-linear? 

**What does "control for" mean?** Imagine you're studying whether social media causes anxiety. You know that stress is a major cause of anxiety, and you also suspect that social media use might cause anxiety. So you need to "control for" stress to see if social media has an independent effect on anxiety. You want to ask: "If two people have the same stress level, does the one who uses more social media have higher anxiety?"

::: {.callout-important}
## 🎯 The Key Insight: Non-Linearity Breaks Even "Good" Regressions

**The problem:** Even when researchers carefully select control variables, non-linear relationships can make linear regression give completely wrong results.

**Why this matters:** If non-linearity can break "proper" causal inference, imagine how much worse it gets when variables are added without careful thought (true "garbage can" regression).

**The connection:** Both scenarios face the same fundamental challenge - linear regression assumes linearity, but real relationships rarely are.
:::

Most researchers assume that if variables are "monotonically related" (meaning: as one variable goes up, the other always goes up or always goes down), then linear regression will give us the right answers. But here's the catch: **linearity is much stronger than monotonicity.**

- **Monotonicity:** A one-unit increase in X always changes Y in the same direction
- **Linearity:** A one-unit increase in X always changes Y by the exact same amount

In practice, we just assume linearity is "close enough" to monotonicity. But what if it's not? What if even small amounts of non-linearity can make our regression results completely wrong?

**The Real-World Context:** We know that stress is a major cause of anxiety, especially for college students. We also suspect that social media use might cause anxiety. So when we study this relationship, we need to control for stress to see the true effect of social media. 

**The Key Problem:** But here's where things get tricky. In practice, we often can't measure stress directly with expensive blood tests. Instead, we use surveys and self-reports. What happens when our "control variable" (stress) is measured imperfectly? What if the relationship between our proxy measure and the true stress level isn't perfectly linear? This is exactly the kind of scenario where linear regression can lead us astray.

**The Devastating Reality:** Even tiny amounts of non-linearity can completely destroy our regression conclusions. A relationship that looks "close enough" to linear can give us coefficients that are completely wrong: wrong signs, wrong magnitudes, wrong interpretations. The regression will confidently report statistically significant results that are fundamentally misleading about the true causal relationships.

Your challenge is to explore the simple example below and show how this happens:

$$
\begin{aligned}
A &\equiv \textrm{Anxiety Level measured by fMRI activity}\\
S &\equiv \textrm{Stress Level measured by cortisol level in blood}\\
T &\equiv \textrm{\# of minutes on social media in last 24 hours}
\end{aligned}
$$

Let's assume we **know** the relationship among these variables is as follows:

$$
Anxiety = Stress + 0.1 \times Time
$$

::: {.callout-important}
## 🔍 Understanding the True Relationship: Implied Coefficients

**Critical Point:** Students often miss that this specific equation implies specific coefficient values in the generic multiple regression framework.

**The Generic Multiple Regression Equation:**
$$
Y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \epsilon
$$

**In Our Case:**
$$
Anxiety = \beta_0 + \beta_1 \times Stress + \beta_2 \times Time + \epsilon
$$

**The True Coefficients (what we "know"):**

- $\beta_0 = 0$ (intercept is zero)
- $\beta_1 = 1$ (coefficient on Stress is 1)  
- $\beta_2 = 0.1$ (coefficient on Time is 0.1)

**Why This Matters:** When we run regression analysis, we're trying to estimate these $\beta$ coefficients. If our regression gives us coefficients that are very different from these true values, we know our model is wrong—even if it has good statistical fit!
::: -->
<section id="the-data-generation-process" class="level3">
<h3 class="anchored" data-anchor-id="the-data-generation-process"><span style="color:brown; font-style:italic;">The Data Generation Process</span></h3>
<div class="cell" data-execution_count="2">
<div id="tbl-observations" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="2">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-observations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Observed data with known true relationships
</figcaption>
<div aria-describedby="tbl-observations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="30">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Stress</th>
<th data-quarto-table-cell-role="th">StressSurvey</th>
<th data-quarto-table-cell-role="th">Time</th>
<th data-quarto-table-cell-role="th">Anxiety</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>0</td>
<td>0</td>
<td>0.0</td>
<td>0.00</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>0</td>
<td>0</td>
<td>1.0</td>
<td>0.10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>0</td>
<td>0</td>
<td>1.0</td>
<td>0.10</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>1</td>
<td>3</td>
<td>1.0</td>
<td>1.10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>1</td>
<td>3</td>
<td>1.0</td>
<td>1.10</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>1</td>
<td>3</td>
<td>1.0</td>
<td>1.10</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>2</td>
<td>6</td>
<td>2.0</td>
<td>2.20</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>2</td>
<td>6</td>
<td>2.0</td>
<td>2.20</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>2</td>
<td>6</td>
<td>2.0</td>
<td>2.20</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>8</td>
<td>9</td>
<td>2.0</td>
<td>8.20</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">10</th>
<td>8</td>
<td>9</td>
<td>2.0</td>
<td>8.20</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">11</th>
<td>8</td>
<td>9</td>
<td>2.1</td>
<td>8.21</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">12</th>
<td>12</td>
<td>12</td>
<td>2.2</td>
<td>12.22</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">13</th>
<td>12</td>
<td>12</td>
<td>2.2</td>
<td>12.22</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">14</th>
<td>12</td>
<td>12</td>
<td>2.2</td>
<td>12.22</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<!-- Notice that $Anxiety = Stress + 0.1 \times Time$ indeed holds perfectly. Also, notice the addition of a `StressSurvey` column. This data was generated by a survey (instead of a blood test) to be a proxy for measuring stress levels using expensive and unpleasant blood tests. You can see it's a good proxy as there is a *monotonic* (and a sorta-kinda *linear*) relationship between the survey results and actual measured stress levels (see @fig-stress-proxy).

::: {.callout-note}
## 📝 Methodological Note: The Contrived Nature of This Example

**Important:** This is a contrived example designed to illustrate the dangers of linear regression. In this simulation:

- **Blood test stress levels** have a perfectly linear relationship with anxiety (by design)
- **Survey stress responses** have a non-linear relationship with anxiety (also by design)

In the real world, there is no reason to believe linearity holds for either measurement method. Both blood tests and surveys would likely show non-linear relationships with anxiety. This example artificially creates the "perfect" scenario where one measurement is linear and the other is not, to demonstrate how regression can mislead us even when we think we're controlling for the right variables.
::: -->
<div id="cell-fig-stress-proxy" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div id="fig-stress-proxy" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stress-proxy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-stress-proxy-output-1.png" width="662" height="374" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stress-proxy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: StressSurvey as a proxy for actual Stress levels
</figcaption>
</figure>
</div>
</div>
</div>
<!-- ## Challenge Requirements 📋

### Minimum Requirements for Any Points on Challenge

1. **Create a Quarto Document:** Use the starter repository (see Repository Setup section below) to begin with a working template. Write a concise quarto markdown file structured as a question and answer document. Each question from the grading rubric should be clearly stated, followed by your answer with analysis, visualizations, and interpretations. **Important:** Your final rendered HTML should contain only your Q&A responses—all challenge instructions, setup guides, and grading rubrics should be removed from the final report.

2. **Render to HTML:** You must render the quarto markdown file to HTML.

3. **GitHub Repository:** Use your forked repository (from the starter repository) named "garbageCanRegressionChallenge" in your GitHub account. Upload your rendered HTML files to this repository.

4. **GitHub Pages Setup:** The repository should be made the source of your github pages:

   - Go to your repository settings (click the "Settings" tab in your GitHub repository)
   - Scroll down to the "Pages" section in the left sidebar
   - Under "Source", select "Deploy from a branch"
   - Choose "main" branch and "/ (root)" folder
   - Click "Save"
   - Your site will be available at: `https://[your-username].github.io/regressionChallenge/`
   - **Note:** It may take a few minutes for the site to become available after enabling Pages

## Getting Started: Repository Setup 🚀

::: {.callout-important}
## 📁 Quick Start with Starter Repository

**Step 1:** Fork the starter repository to your github account at [https://github.com/flyaflya/regressionChallenge.git](https://github.com/flyaflya/regressionChallenge.git)

**Step 2:** Clone your fork locally using Cursor (or VS Code)

**Step 3:** You're ready to start! The repository includes pre-loaded data and a working template.
:::

::: {.callout-tip}
## 💡 Why Use the Starter Repository?

**Benefits:**

- **Pre-loaded data:** All required data (`observDF` with Stress, StressSurvey, Time, Anxiety) is included
- **Working template:** Basic Quarto structure (`index.qmd`) is ready
- **No setup errors:** Avoid common data loading issues
- **Focus on analysis:** Spend time on regression analysis, not data preparation
:::

### Getting Started Tips

::: {.callout-note}
## 🎯 Navy SEALs Motto

> "Slow is Smooth and Smooth is Fast"

*Take your time to understand the regression mechanics, plan your approach carefully, and execute with precision. Rushing through this challenge will only lead to errors and confusion.*
:::

::: {.callout-warning}
## 💾 Important: Save Your Work Frequently!

**Before you start coding:** Make sure to commit your work often using the Source Control panel in Cursor (Ctrl+Shift+G or Cmd+Shift+G). This prevents the AI from overwriting your progress and ensures you don't lose your work.

**Commit after each major step:**

- After completing each regression analysis
- After finishing each challenge question
- Before asking the AI for help with new code

**How to commit:**

1. Open Source Control panel (Ctrl+Shift+G)
2. Stage your changes (+ button)
3. Write a descriptive commit message
4. Click the checkmark to commit

*Remember: Frequent commits are your safety net!*
:::

## Grading Rubric 🎓

::: {.callout-important}
## 📊 What You're Really Being Graded On

**This is an investigative report, not a coding exercise.** You're analyzing regression models and reporting your findings like a professional analyst would. Think of this as a brief you'd write for a client or manager about why they should be skeptical of regression results.

**Report Format:**

- **Question and Answer Format:** Your final report should be structured as a question and answer document. Each question from the grading rubric should be clearly stated, followed by your answer with analysis, visualizations, and interpretations.
- **Delete All Challenge Instructions:** Once you've completed your analysis, remove all challenge instructions, setup guides, and grading rubrics from your final rendered HTML. The final report should contain only your Q&A responses, code outputs, and visualizations—nothing else.
- **Hidden Code:** Tell a narrative and visual story, but hide your code (the code can be referenced in your github *.qmd source file if needed).
- **Use convention of dependent variable on the vertical axis:** When plotting, put the dependent variable (i.e., Anxiety) on the vertical axis.  Independent variables (i.e., StressSurvey, Stress, and Time) should be on the horizontal axis.

**What makes a great report:**

- **Clear narrative:** Tell the story of what you discovered about regression interpretability
- **Insightful analysis:** Focus on the most interesting differences between true relationships and estimated relationships
- **Professional presentation:** Clean, readable, and engaging
- **Concise conclusions:** No AI babble or unnecessary technical jargon
- **Human insights:** Your interpretation of what the regression coefficients actually mean (or don't mean)

**What we're looking for:** A compelling 4-8 minute read that demonstrates both the power of linear models for interpretation and the critical pitfalls of over-relying on statistical significance in regression analysis.
::: -->
<!-- ### Questions to Answer for 75% Grade on Challenge  -->
</section>
</section>
<section id="question-1.-bivariate-regression-analysis-with-stresssurvey" class="level2">
<h2 class="anchored" data-anchor-id="question-1.-bivariate-regression-analysis-with-stresssurvey"><span style="color:brown; font-style:italic;">Question 1. Bivariate Regression Analysis with StressSurvey:</span></h2>
<p>Run a bivariate regression of Anxiety on StressSurvey. What are the estimated coefficients? How do they compare to the true relationship?</p>
<p><span style="color:brown; font-style:italic; font-weight:bold;">Answer:</span></p>
<div id="5764336c" class="cell" data-execution_count="4">
<div class="cell-output cell-output-stdout">
<pre><code>Bivariate Regression: Anxiety ~ StressSurvey
==================================================
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       0.901
Model:                            OLS   Adj. R-squared:                  0.893
Method:                 Least Squares   F-statistic:                     118.4
Date:                Wed, 12 Nov 2025   Prob (F-statistic):           6.68e-08
Time:                        22:37:45   Log-Likelihood:                -27.079
No. Observations:                  15   AIC:                             58.16
Df Residuals:                      13   BIC:                             59.57
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const           -1.5240      0.707     -2.156      0.050      -3.051       0.003
StressSurvey     1.0470      0.096     10.883      0.000       0.839       1.255
==============================================================================
Omnibus:                        2.125   Durbin-Watson:                   0.545
Prob(Omnibus):                  0.346   Jarque-Bera (JB):                1.642
Skew:                          -0.701   Prob(JB):                        0.440
Kurtosis:                       2.186   Cond. No.                         12.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

==================================================

Estimated Intercept: -1.5240
Estimated StressSurvey Coefficient: 1.0470
R-squared: 0.9011

True relationship: Anxiety = Stress + 0.1 × Time
Note: This model uses StressSurvey, not Stress, so direct comparison is not straightforward.</code></pre>
</div>
</div>
<p>The bivariate regression of Anxiety on StressSurvey yields an intercept of approximately 0.00 and a StressSurvey coefficient of approximately 1.0470. The R-squared is very high (0.9011), suggesting an excellent fit.</p>
<p>However, this comparison is misleading because we’re regressing Anxiety on StressSurvey, not on the true Stress variable. The true relationship involves Stress (not StressSurvey) and Time. The coefficient of 1.0470 reflects the actual relationship between StressSurvey and Anxiety in the data, but the model is missing the Time variable entirely, which biases the interpretation. When Time is omitted, the StressSurvey coefficient captures both the effect of stress (through StressSurvey) and any correlation between StressSurvey and Time, leading to a biased estimate of the true relationship.</p>
<hr>
</section>
<section id="question-2.-visualization-of-bivariate-relationship" class="level2">
<h2 class="anchored" data-anchor-id="question-2.-visualization-of-bivariate-relationship"><span style="color:brown; font-style:italic;">Question 2. Visualization of Bivariate Relationship:</span></h2>
<p>Create a scatter plot with the regression line showing the relationship between StressSurvey and Anxiety. Comment on the fit and any potential issues.</p>
<p><span style="color:brown; font-style:italic; font-weight:bold;">Answer:</span></p>
<div id="cell-fig-stress-survey-bivariate" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div id="fig-stress-survey-bivariate" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stress-survey-bivariate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-stress-survey-bivariate-output-1.png" width="758" height="469" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stress-survey-bivariate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Bivariate relationship between StressSurvey and Anxiety with regression line
</figcaption>
</figure>
</div>
</div>
</div>
<p>The scatter plot shows an extremely tight linear relationship between StressSurvey and Anxiety, with an R-squared of 0.9011. The regression line fits the data points almost perfectly.</p>
<p><strong>Potential Issues:</strong></p>
<ol type="1">
<li><p><strong>Missing Variable Bias:</strong> The model omits Time, which is part of the true relationship. This means the StressSurvey coefficient captures both the effect of stress and any correlation between StressSurvey and Time.</p></li>
<li><p><strong>Non-Linearity Masked:</strong> While the relationship appears linear in this bivariate view, the underlying relationship between StressSurvey and the true Stress variable is non-linear. This non-linearity will cause problems when we add Time to the model.</p></li>
<li><p><strong>Spurious Precision:</strong> The high R-squared gives false confidence. The model appears perfect, but it’s estimating the wrong relationship because it’s missing a key variable.</p></li>
</ol>
<hr>
</section>
<section id="question-3.-bivariate-regression-analysis-with-time" class="level2">
<h2 class="anchored" data-anchor-id="question-3.-bivariate-regression-analysis-with-time"><span style="color:brown; font-style:italic;">Question 3. Bivariate Regression Analysis with Time:</span></h2>
<p>Run a bivariate regression of Anxiety on Time. What are the estimated coefficients? How do they compare to the true relationship?</p>
<p><span style="color:brown; font-style:italic; font-weight:bold;">Answer:</span></p>
<div id="ada39c08" class="cell" data-execution_count="6">
<div class="cell-output cell-output-stdout">
<pre><code>Bivariate Regression: Anxiety ~ Time
==================================================
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       0.563
Model:                            OLS   Adj. R-squared:                  0.529
Method:                 Least Squares   F-statistic:                     16.75
Date:                Wed, 12 Nov 2025   Prob (F-statistic):            0.00127
Time:                        22:37:45   Log-Likelihood:                -38.223
No. Observations:                  15   AIC:                             80.45
Df Residuals:                      13   BIC:                             81.86
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -3.6801      2.233     -1.648      0.123      -8.504       1.144
Time           5.3406      1.305      4.093      0.001       2.522       8.160
==============================================================================
Omnibus:                        1.026   Durbin-Watson:                   0.661
Prob(Omnibus):                  0.599   Jarque-Bera (JB):                0.749
Skew:                          -0.162   Prob(JB):                        0.688
Kurtosis:                       1.955   Cond. No.                         5.80
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

==================================================

Estimated Intercept: -3.6801
Estimated Time Coefficient: 5.3406
R-squared: 0.5630

True relationship: Anxiety = Stress + 0.1 × Time
True Time coefficient: 0.1

Comparison: The estimated coefficient (5.3406) is MUCH larger than the true coefficient (0.1)</code></pre>
</div>
</div>
<p>The bivariate regression of Anxiety on Time yields an intercept of approximately -3.6801 and a Time coefficient of approximately 5.3406. The R-squared is 0.5630, indicating a moderate fit—the model explains about 56% of the variation in Anxiety.</p>
<p><strong>Critical Finding:</strong> The estimated Time coefficient (5.3406) is <strong>approximately 53 times larger</strong> than the true coefficient (0.1)! This massive overestimation occurs because Time is correlated with Stress in the data. When we omit Stress from the model, the Time coefficient absorbs the effect of Stress, leading to a severely biased estimate.</p>
<p>This demonstrates the classic omitted variable bias problem: when a relevant variable (Stress) is excluded from the regression, the coefficients on included variables become biased.</p>
<hr>
</section>
<section id="question-4.-visualization-of-bivariate-relationship" class="level2">
<h2 class="anchored" data-anchor-id="question-4.-visualization-of-bivariate-relationship"><span style="color:brown; font-style:italic;">Question 4. Visualization of Bivariate Relationship:</span></h2>
<p>Create a scatter plot with the regression line showing the relationship between Time and Anxiety. Comment on the fit and any potential issues.</p>
<p><span style="color:brown; font-style:italic; font-weight:bold;">Answer:</span></p>
<div id="cell-fig-time-bivariate" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<div id="fig-time-bivariate" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-time-bivariate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-time-bivariate-output-1.png" width="758" height="469" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-time-bivariate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Bivariate relationship between Time and Anxiety with regression line
</figcaption>
</figure>
</div>
</div>
</div>
<p>The scatter plot shows a positive linear relationship between Time and Anxiety, with an R-squared of 0.5630. While there is a clear pattern, the fit is only moderate—the model explains about 56% of the variation in Anxiety.</p>
<p><strong>Critical Issues:</strong></p>
<ol type="1">
<li><p><strong>Severe Omitted Variable Bias:</strong> The model completely omits Stress, which is the dominant factor in the true relationship. The Time coefficient of 5.3406 is approximately 53 times too large because it’s capturing the effect of Stress (which is correlated with Time in this dataset).</p></li>
<li><p><strong>Misleading Interpretation:</strong> A researcher might conclude that social media use has a massive effect on anxiety (coefficient = 5.3406), when in reality the true effect is tiny (coefficient = 0.1). This could lead to completely wrong policy recommendations.</p></li>
<li><p><strong>Misleading Despite Moderate Fit:</strong> Even with a moderate R-squared (0.5630), the model is estimating the wrong causal relationship. The coefficient is severely biased due to omitted variable bias.</p></li>
</ol>
<hr>
</section>
<section id="question-5.-multiple-regression-analysis" class="level2">
<h2 class="anchored" data-anchor-id="question-5.-multiple-regression-analysis"><span style="color:brown; font-style:italic;">Question 5. Multiple Regression Analysis:</span></h2>
<p>Run a multiple regression of Anxiety on both <strong>StressSurvey</strong> and Time. What are the estimated coefficients? How do they compare to the true relationship?</p>
<p><span style="color:brown; font-style:italic; font-weight:bold;">Answer:</span></p>
<div id="339f5b47" class="cell" data-execution_count="8">
<div class="cell-output cell-output-stdout">
<pre><code>Multiple Regression: Anxiety ~ StressSurvey + Time
============================================================
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       0.935
Model:                            OLS   Adj. R-squared:                  0.924
Method:                 Least Squares   F-statistic:                     86.32
Date:                Wed, 12 Nov 2025   Prob (F-statistic):           7.54e-08
Time:                        22:37:45   Log-Likelihood:                -23.931
No. Observations:                  15   AIC:                             53.86
Df Residuals:                      12   BIC:                             55.99
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const            0.5888      1.034      0.569      0.580      -1.664       2.841
StressSurvey     1.4269      0.172      8.287      0.000       1.052       1.802
Time            -2.7799      1.111     -2.502      0.028      -5.201      -0.359
==============================================================================
Omnibus:                        1.255   Durbin-Watson:                   1.043
Prob(Omnibus):                  0.534   Jarque-Bera (JB):                1.051
Skew:                           0.546   Prob(JB):                        0.591
Kurtosis:                       2.302   Cond. No.                         31.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

============================================================

Estimated Intercept: 0.5888
Estimated StressSurvey Coefficient: 1.4269
Estimated Time Coefficient: -2.7799
R-squared: 0.9350

============================================================
COMPARISON TO TRUE RELATIONSHIP:
============================================================
True relationship: Anxiety = Stress + 0.1 × Time
True Intercept (β₀): 0.0
True Stress coefficient (β₁): 1.0
True Time coefficient (β₂): 0.1

Estimated vs True:
  Intercept: 0.5888 vs 0.0
  StressSurvey: 1.4269 vs 1.0 (Stress)
  Time: -2.7799 vs 0.1

⚠️  CRITICAL: The Time coefficient has the WRONG SIGN!
   Estimated: -2.7799 (NEGATIVE)
   True: 0.1 (POSITIVE)</code></pre>
</div>
</div>
<p><strong>Shocking Result:</strong> The multiple regression with StressSurvey and Time produces coefficients that are completely wrong:</p>
<ul>
<li><strong>Intercept:</strong> 0.5888 (true: 0.0) — not zero as expected</li>
<li><strong>StressSurvey:</strong> 1.4269 (true Stress: 1.0) — appears close, but this is misleading</li>
<li><strong>Time:</strong> <strong>-2.7799</strong> (true: 0.1) — <strong>WRONG SIGN and WRONG MAGNITUDE!</strong></li>
</ul>
<p><strong>The Devastating Finding:</strong> The Time coefficient is <strong>negative</strong> (-2.7799) when the true coefficient is <strong>positive</strong> (0.1). This is a complete reversal of the true relationship! Not only is the sign wrong, but the magnitude is also dramatically incorrect—the estimated coefficient is approximately 28 times larger in absolute value than the true coefficient, but in the opposite direction. The model suggests that more time on social media <em>reduces</em> anxiety substantially, when in reality it <em>increases</em> anxiety modestly.</p>
<p><strong>Why This Happens:</strong> The non-linear relationship between StressSurvey and the true Stress variable creates a situation where, after controlling for StressSurvey, the residual variation in Anxiety is negatively correlated with Time. This is a classic example of how non-linearity in control variables can completely reverse the sign of coefficients, even when the proxy variable (StressSurvey) appears to be a good measure.</p>
<p>The R-squared is high (0.9350), making this result even more dangerous—it looks like a good model, but the coefficients tell a completely false story.</p>
<hr>
<!-- ::: {.callout-tip}
## 🎯 Remember the True Coefficients!

When analyzing your multiple regression results, compare them to the **true relationship** we established:

**True Coefficients:**

- Intercept ($\beta_0$) = 0
- Stress coefficient ($\beta_1$) = 1  
- Time coefficient ($\beta_2$) = 0.1

**Key Questions:**

- Are your estimated coefficients close to these true values?
- If not, what does this tell you about the reliability of your regression model?
- Even if your R-squared is high, are the coefficients telling the right story?
:::

### Questions to Answer for 85% Grade on Challenge -->
</section>
<section id="question-6.-multiple-regression-analysis" class="level2">
<h2 class="anchored" data-anchor-id="question-6.-multiple-regression-analysis"><span style="color:brown; font-style:italic;">Question 6. Multiple Regression Analysis:</span></h2>
<p>Run a multiple regression of Anxiety on both <strong>Stress</strong> and Time. What are the estimated coefficients? How do they compare to the true relationship?</p>
<p><span style="color:brown; font-style:italic; font-weight:bold;">Answer:</span></p>
<div id="fa242d62" class="cell" data-execution_count="9">
<div class="cell-output cell-output-stdout">
<pre><code>Multiple Regression: Anxiety ~ Stress + Time
============================================================
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 1.511e+31
Date:                Wed, 12 Nov 2025   Prob (F-statistic):          3.92e-183
Time:                        22:37:45   Log-Likelihood:                 480.58
No. Observations:                  15   AIC:                            -955.2
Df Residuals:                      12   BIC:                            -953.0
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P&gt;|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -3.747e-15   2.44e-15     -1.538      0.150   -9.05e-15    1.56e-15
Stress         1.0000   2.75e-16   3.63e+15      0.000       1.000       1.000
Time           0.1000   1.94e-15   5.16e+13      0.000       0.100       0.100
==============================================================================
Omnibus:                       10.194   Durbin-Watson:                   0.236
Prob(Omnibus):                  0.006   Jarque-Bera (JB):                2.265
Skew:                          -0.438   Prob(JB):                        0.322
Kurtosis:                       1.310   Cond. No.                         23.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

============================================================

Estimated Intercept: -0.0000
Estimated Stress Coefficient: 1.0000
Estimated Time Coefficient: 0.1000
R-squared: 1.0000

============================================================
COMPARISON TO TRUE RELATIONSHIP:
============================================================
True relationship: Anxiety = Stress + 0.1 × Time
True Intercept (β₀): 0.0
True Stress coefficient (β₁): 1.0
True Time coefficient (β₂): 0.1

Estimated vs True:
  Intercept: -0.0000 vs 0.0
  Stress: 1.0000 vs 1.0
  Time: 0.1000 vs 0.1

✅ PERFECT MATCH: All coefficients match the true relationship!</code></pre>
</div>
</div>
<p><strong>Perfect Recovery:</strong> When we use the true Stress variable (instead of StressSurvey), the multiple regression recovers the true coefficients exactly:</p>
<ul>
<li><strong>Intercept:</strong> 0.00 (true: 0.0) ✅</li>
<li><strong>Stress:</strong> 1.00 (true: 1.0) ✅<br>
</li>
<li><strong>Time:</strong> 0.10 (true: 0.1) ✅</li>
</ul>
<p>The R-squared is 1.000 (perfect fit), and all coefficients match the true relationship perfectly. This demonstrates that when the control variable has a truly linear relationship with the outcome, multiple regression works exactly as expected.</p>
<p><strong>The Key Contrast:</strong> Using the true Stress variable gives us the correct answer, while using StressSurvey (the proxy) gives us completely wrong coefficients, including a sign reversal for Time. This is the core problem: even a “good” proxy variable can lead to catastrophic errors if its relationship with the outcome is non-linear.</p>
<hr>
</section>
<section id="question-7.-model-comparison" class="level2">
<h2 class="anchored" data-anchor-id="question-7.-model-comparison"><span style="color:brown; font-style:italic;">Question 7. Model Comparison:</span></h2>
<p>Compare the R-squared values and coefficient interpretations between the two multiple regression models. Do both models show statistical significance in all of their coefficient estimates? What does this tell you about the real-world implications of multiple regression results?</p>
<p><span style="color:brown; font-style:italic; font-weight:bold; text-align:justify;">Answer:</span></p>
<div id="cee04015" class="cell" data-execution_count="10">
<div class="cell-output cell-output-stdout">
<pre><code>MODEL COMPARISON
================================================================================
              Model     Intercept  Stress/StressSurvey Coef  Time Coef  R-squared  Stress/StressSurvey p-value  Time p-value Stress/StressSurvey Sig Time Sig
StressSurvey + Time  5.887578e-01                  1.426926  -2.779944   0.935005                 2.615836e-06  2.781595e-02                     Yes      Yes
      Stress + Time -3.747003e-15                  1.000000   0.100000   1.000000                1.270138e-181 1.890990e-159                     Yes      Yes

================================================================================

STATISTICAL SIGNIFICANCE ANALYSIS:
================================================================================

Model 1 (StressSurvey + Time):
  StressSurvey: p-value = 2.62e-06 → Statistically Significant
  Time: p-value = 2.78e-02 → Statistically Significant

Model 2 (Stress + Time):
  Stress: p-value = 1.27e-181 → Statistically Significant
  Time: p-value = 1.89e-159 → Statistically Significant

================================================================================

KEY FINDINGS:
================================================================================
1. Both models have good R-squared (0.9350 vs 1.000)
2. Both models show statistical significance (p &lt; 0.05) for ALL coefficients
3. Model 1 (StressSurvey) has WRONG SIGN for Time coefficient
4. Model 2 (Stress) has CORRECT coefficients matching true relationship

⚠️  CRITICAL INSIGHT: Statistical significance does NOT guarantee correct results!</code></pre>
</div>
</div>
<p><strong>Model Comparison Summary:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 11%">
<col style="width: 26%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th>Intercept</th>
<th>Stress/StressSurvey Coef</th>
<th>Time Coef</th>
<th>R-squared</th>
<th>All Coefficients Significant?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>StressSurvey + Time</td>
<td>0.5888</td>
<td>1.4269</td>
<td><strong>-2.7799</strong></td>
<td>0.9350</td>
<td>✅ Yes</td>
</tr>
<tr class="even">
<td>Stress + Time</td>
<td>0.00</td>
<td>1.00</td>
<td><strong>0.10</strong></td>
<td>1.000</td>
<td>✅ Yes</td>
</tr>
</tbody>
</table>
<p><strong>Critical Findings:</strong></p>
<ol type="1">
<li><p><strong>Both models have good fit:</strong> R-squared values are 0.9350 and 1.000, suggesting both models fit the data well.</p></li>
<li><p><strong>Both models show statistical significance:</strong> All coefficients in both models have p-values &lt; 0.05, meaning they are statistically significant.</p></li>
<li><p><strong>But the coefficients tell opposite stories:</strong></p>
<ul>
<li>Model 1 (StressSurvey): Time coefficient = -2.7799 (negative)</li>
<li>Model 2 (Stress): Time coefficient = 0.10 (positive)</li>
</ul></li>
</ol>
<p><strong>Real-World Implications:</strong></p>
<p>This comparison reveals a devastating truth about regression analysis: <strong>statistical significance and high R-squared do not guarantee correct results.</strong></p>
<p>In practice, researchers often: - Use proxy variables (like surveys instead of blood tests) because they’re cheaper or easier to collect - Rely on statistical significance (p &lt; 0.05) as proof that their results are correct - Report high R-squared values as evidence of model quality</p>
<p>But as this analysis shows, a model can be: - ✅ Statistically significant (all p-values &lt; 0.05) - ✅ High R-squared (0.9350) - ❌ Completely wrong (wrong sign, wrong magnitude)</p>
<p><strong>The Danger:</strong> If Model 1 were published, researchers would confidently report that “controlling for stress survey responses, social media use significantly reduces anxiety (β = -2.7799, p &lt; 0.05).” This conclusion would be statistically valid but causally wrong—the true effect is positive (0.1), not negative (-2.7799).</p>
<p>This demonstrates why we must be skeptical of regression results, especially when: - Using proxy variables instead of direct measurements - Relationships might be non-linear - Results seem too good to be true (perfect fit, all significant)</p>
<hr>
<!-- ### Questions to Answer for 95% Grade on Challenge -->
</section>
<section id="question-8.-reflect-on-real-world-implications" class="level2">
<h2 class="anchored" data-anchor-id="question-8.-reflect-on-real-world-implications"><span style="color:brown; font-style:italic;">Question 8. Reflect on Real-World Implications:</span></h2>
<p>For each of the two multiple regression models, assume their respective outputs/conclusions were published in academic journals and then subsequently picked up by the popular press. What headline about time spent on social media and its effect on anxiety would you expect to see from a popular press outlet covering the first model? And what headline would you expect to see from a popular press outlet covering the second model? Assuming confirmation bias is real, which model is a typical parent going to believe? Which model will Facebook, Instagram, and TikTok executives prefer?</p>
<p><span style="color:brown; font-style:italic; font-weight:bold; text-align:justify;">Answer:</span></p>
<section id="model-1-stresssurvey-time-headline" class="level3">
<h3 class="anchored" data-anchor-id="model-1-stresssurvey-time-headline">Model 1 (StressSurvey + Time) Headline:</h3>
<p><strong>“BREAKING: New Study Finds Social Media Use Actually REDUCES Anxiety”</strong></p>
<p><em>Subheadline: “Researchers control for stress levels and discover surprising benefit of screen time”</em></p>
<p>The popular press would emphasize the counterintuitive finding: social media reduces anxiety. This would be framed as a “surprising” or “controversial” result that challenges conventional wisdom. The article would likely quote the researchers saying something like “After controlling for stress, we found that each additional minute of social media use was associated with a 2.78-point reduction in anxiety levels (p &lt; 0.05).”</p>
</section>
<section id="model-2-stress-time-headline" class="level3">
<h3 class="anchored" data-anchor-id="model-2-stress-time-headline">Model 2 (Stress + Time) Headline:</h3>
<p><strong>“Study Confirms: Social Media Increases Anxiety, But Effect Is Small”</strong></p>
<p><em>Subheadline: “Research shows modest link between screen time and anxiety when properly controlling for stress”</em></p>
<p>The popular press would report the more intuitive finding: social media increases anxiety. However, they might downplay the small effect size (0.10), focusing instead on the statistical significance. The article might say “The study found that social media use significantly increases anxiety, with each additional minute associated with a 0.10-point increase (p &lt; 0.05).”</p>
</section>
<section id="who-believes-what" class="level3">
<h3 class="anchored" data-anchor-id="who-believes-what">Who Believes What?</h3>
<p><strong>Typical Parent:</strong> Parents would <strong>strongly prefer Model 1</strong> due to confirmation bias. Most parents are already concerned about their children’s social media use and want to believe it’s harmful. However, Model 1 tells them the opposite—that social media reduces anxiety. This creates cognitive dissonance. But here’s the twist: if Model 1 were the only study published, some parents might use it to justify allowing more screen time (“See? The science says it’s actually good for them!”). However, most parents would likely dismiss Model 1 as flawed or look for other studies that confirm their pre-existing beliefs.</p>
<p><strong>Social Media Executives (Facebook, Instagram, TikTok):</strong> Executives would <strong>strongly prefer Model 1</strong> because it suggests their products reduce anxiety rather than increase it. They would: - Fund press releases highlighting the “surprising” finding - Use it in marketing materials (“Research shows our platform may reduce anxiety”) - Cite it when defending against criticism - Potentially fund follow-up studies to replicate the finding</p>
<p>Model 2 would be problematic for them because it confirms public concerns about social media’s negative effects, even if the effect is small.</p>
<p><strong>The Real Danger:</strong> This scenario illustrates how statistical errors can have real-world consequences. If Model 1 were published first and received media attention, it could: 1. Mislead parents about the effects of social media 2. Be used by tech companies to defend their products 3. Create confusion when Model 2 (or other correct studies) are published later 4. Undermine public trust in scientific research when the contradiction becomes apparent</p>
<p><strong>The Lesson:</strong> This is why rigorous methodology matters. Using the wrong control variable (even if it seems like a good proxy) can produce results that are not just wrong, but wrong in a way that serves particular interests—making them especially dangerous.</p>
<hr>
<!-- ### Questions to Answer for 100% Grade on Challenge -->
</section>
</section>
<section id="question-9.-avoiding-misleading-statistical-significance" class="level2">
<h2 class="anchored" data-anchor-id="question-9.-avoiding-misleading-statistical-significance"><span style="color:brown; font-style:italic;">Question 9. Avoiding Misleading Statistical Significance:</span></h2>
<p>Reflect on this tip to avoid being misled by statistically significant results: splitting the sample into meaningful subsets (“statistical regimes”), and using graphical diagnostics for linearity rather than blind reliance on “canned” regressions. Apply this approach to multiple regression of Anxiety on both StressSurvey and Time by analyzing a smartly chosen subset of the data. What specific subset did you choose and why? Did you get results that are both statistically significant and close to the true relationship?</p>
<p><span style="color:brown; font-style:italic; font-weight:bold; text-align:justify;">Answer:</span></p>
<p>The key insight is to identify “statistical regimes” where the relationship might be more linear. Looking at the data, I notice that the non-linearity in the StressSurvey-Stress relationship is most pronounced at the extremes. Let me examine the relationship more carefully and choose a subset where StressSurvey and Stress have a more linear relationship.</p>
<div id="d495a8ed" class="cell" data-fig-dpi="100" data-fig-height="3.2" data-fig-width="7" data-execution_count="11">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-12-output-1.png" width="683" height="318" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Subset Selection Rationale:
============================================================
I chose observations where Stress ≤ 2 because:
1. In this range, StressSurvey = 3 × Stress (perfectly linear)
2. The relationship StressSurvey-Stress is linear: 0→0, 1→3, 2→6
3. This avoids the non-linear jump at Stress=8 (StressSurvey=9)
4. This subset represents a 'statistical regime' with consistent linearity

Subset size: 9 observations (out of 15 total)</code></pre>
</div>
</div>
<p><strong>Subset Selection:</strong> I chose observations where <strong>Stress ≤ 2</strong> because:</p>
<ol type="1">
<li><p><strong>Linear Relationship:</strong> In this range, StressSurvey = 3 × Stress, which is perfectly linear (0→0, 1→3, 2→6).</p></li>
<li><p><strong>Avoids Non-Linearity:</strong> This subset excludes the non-linear jump where Stress jumps from 2 to 8, but StressSurvey only increases from 6 to 9.</p></li>
<li><p><strong>Meaningful Regime:</strong> This represents a “low-to-moderate stress” regime where the proxy variable maintains a linear relationship with the true variable.</p></li>
</ol>
<p>Now let’s run the multiple regression on this subset:</p>
<div id="9837673f" class="cell" data-execution_count="12">
<div class="cell-output cell-output-stdout">
<pre><code>Multiple Regression on Subset: Anxiety ~ StressSurvey + Time
(Subset: Stress ≤ 2)
======================================================================
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                Anxiety   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 4.892e+30
Date:                Wed, 12 Nov 2025   Prob (F-statistic):           2.31e-91
Time:                        22:37:45   Log-Likelihood:                 301.52
No. Observations:                   9   AIC:                            -597.0
Df Residuals:                       6   BIC:                            -596.4
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
================================================================================
                   coef    std err          t      P&gt;|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const        -3.386e-16   6.61e-16     -0.512      0.627   -1.96e-15    1.28e-15
StressSurvey     0.3333   2.27e-16   1.47e+15      0.000       0.333       0.333
Time             0.1000   8.87e-16   1.13e+14      0.000       0.100       0.100
==============================================================================
Omnibus:                        4.107   Durbin-Watson:                   0.613
Prob(Omnibus):                  0.128   Jarque-Bera (JB):                2.122
Skew:                           1.174   Prob(JB):                        0.346
Kurtosis:                       2.615   Cond. No.                         15.8
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

======================================================================

Estimated Intercept: -0.0000
Estimated StressSurvey Coefficient: 0.3333
Estimated Time Coefficient: 0.1000
R-squared: 1.0000

======================================================================
COMPARISON TO TRUE RELATIONSHIP:
======================================================================
True relationship: Anxiety = Stress + 0.1 × Time
True Intercept (β₀): 0.0
True Stress coefficient (β₁): 1.0
True Time coefficient (β₂): 0.1

Estimated vs True:
  Intercept: -0.0000 vs 0.0
  StressSurvey: 0.3333 vs 1.0 (Stress)
  Time: 0.1000 vs 0.1

======================================================================
STATISTICAL SIGNIFICANCE:
======================================================================
StressSurvey p-value: 0.0000 → Significant
Time p-value: 0.0000 → Significant</code></pre>
</div>
</div>
<p><strong>Results on Subset (Stress ≤ 2):</strong></p>
<ul>
<li><strong>Intercept:</strong> 0.00 (true: 0.0) ✅ Perfect match</li>
<li><strong>StressSurvey Coefficient:</strong> 0.33 (true Stress: 1.0) ⚠️ Different magnitude</li>
<li><strong>Time Coefficient:</strong> 0.10 (true: 0.1) ✅ Perfect match!</li>
<li><strong>R-squared:</strong> 1.000 (perfect fit)</li>
<li><strong>Statistical Significance:</strong> Both coefficients are statistically significant (p &lt; 0.05)</li>
</ul>
<p><strong>Key Findings:</strong></p>
<ol type="1">
<li><p><strong>Time Coefficient Recovery:</strong> The Time coefficient (0.10) matches the true value perfectly! This is a dramatic improvement over the full-sample model, which gave us -2.7799 (wrong sign and wrong magnitude).</p></li>
<li><p><strong>StressSurvey Coefficient:</strong> The coefficient is 0.33 instead of 1.0, but this makes sense because in this subset, StressSurvey = 3 × Stress. So if the true relationship is Anxiety = Stress + 0.1×Time, and StressSurvey = 3×Stress, then Anxiety = (1/3)×StressSurvey + 0.1×Time. The coefficient 0.33 = 1/3, which is exactly what we’d expect!</p></li>
<li><p><strong>Statistical Significance:</strong> Both coefficients are statistically significant, so we have both significance AND correctness (at least for the Time coefficient).</p></li>
</ol>
<p><strong>Why This Works:</strong></p>
<p>By splitting the sample into a regime where StressSurvey has a linear relationship with Stress, we avoid the non-linearity that was causing the sign reversal. In this subset: - StressSurvey = 3 × Stress (linear transformation) - The relationship Anxiety = Stress + 0.1×Time can be rewritten as Anxiety = (1/3)×StressSurvey + 0.1×Time - The regression correctly estimates both coefficients</p>
<p><strong>The Lesson:</strong></p>
<p>This demonstrates the power of <strong>graphical diagnostics and regime analysis</strong>:</p>
<ol type="1">
<li><strong>Visualize relationships first:</strong> Plot StressSurvey vs Stress to identify where non-linearity occurs</li>
<li><strong>Split into meaningful regimes:</strong> Analyze subsets where relationships are more linear</li>
<li><strong>Compare results:</strong> If results differ dramatically across regimes, that’s a red flag</li>
<li><strong>Don’t trust “canned” regressions blindly:</strong> Always examine the data structure before running regressions</li>
</ol>
<p><strong>Practical Implication:</strong></p>
<p>In real-world research, this approach would involve: - Plotting control variables against outcomes to check for non-linearity - Identifying natural breakpoints or regimes in the data - Running separate analyses for each regime - Comparing results across regimes to check robustness - Being skeptical if results change dramatically across regimes</p>
<p>This is exactly the kind of careful analysis that prevents the catastrophic errors we saw in the full-sample model with StressSurvey.</p>
<hr>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion"><span style="color:brown; font-style:italic;">Conclusion</span></h2>
<p>This analysis demonstrates that <strong>statistically significant results with high R-squared can be fundamentally incorrect</strong> when the assumption of linearity is violated, particularly when proxy variables with non-linear relationships are used as control variables.</p>
<section id="key-takeaways" class="level3">
<h3 class="anchored" data-anchor-id="key-takeaways"><span style="color:brown; font-style:italic;">Key Takeaways</span></h3>
<ol type="1">
<li><p><span style="color:maroon; font-style:italic;"><strong>Proxy variables can mislead:</strong></span> Even “good” proxies (like StressSurvey) can produce wrong coefficients if their relationship with the outcome is non-linear. In our analysis, StressSurvey produced a Time coefficient of -2.7799 (significant, p &lt; 0.05), while the true coefficient is +0.1—a complete sign reversal.</p></li>
<li><p><span style="color:maroon; font-style:italic;"><strong>Statistical significance ≠ correctness:</strong></span> Both models showed statistical significance, but one had the wrong sign for the Time coefficient. Significance alone cannot distinguish correct from incorrect models when linearity is violated.</p></li>
<li><p><span style="color:maroon; font-style:italic;"><strong>High R-squared ≠ truth:</strong></span> A model can fit the data well (R² = 0.9350) while telling a completely false story. Model fit does not guarantee accurate coefficient estimates or correct causal interpretations.</p></li>
<li><p><span style="color:maroon; font-style:italic;"><strong>Regime analysis helps:</strong></span> Splitting the sample into subsets with more linear relationships can recover correct coefficients. By analyzing the subset where Stress ≤ 2, we recovered the correct Time coefficient (0.10), matching the true parameter value.</p></li>
<li><p><span style="color:maroon; font-style:italic;"><strong>Visual diagnostics are essential:</strong></span> Graphical analysis and regime identification are critical for detecting non-linearity and preventing misleading regression results. Always plot relationships before trusting regression outputs.</p></li>
</ol>
<div class="columns">
<div class="column" style="width:48%;">
<div class="cell" data-layout-align="default">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode default code-with-copy"><code class="sourceCode default"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>flowchart TD</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    classDef problem fill:#FFE6E6,stroke:#CC0000,color:#660000,font-weight:bold,font-size:12px</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    classDef node fill:#F0F0F0,stroke:#666666,stroke-width:2px,color:#000000,font-weight:bold</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    subgraph Problem["THE PROBLEM"]</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>        class Problem problem</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>        style Problem fill:#FFE6E6,stroke:#CC0000,stroke-width:2.5px,color:#660000,padding:10px</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>        P1["Non-Linear Proxy&lt;br/&gt;Variables"]:::node --&gt;|"Leads to"| P2["Wrong Coefficient&lt;br/&gt;Signs &amp; Magnitudes"]:::node</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>        P3["High R² + Significant&lt;br/&gt;p-values"]:::node --&gt;|"Creates illusion of"| P4["Valid Results"]:::node</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>        P2 --&gt; P5["Misleading Policy&lt;br/&gt;Recommendations"]:::node</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>        P4 --&gt; P5</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>    end</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
    classDef problem fill:#FFE6E6,stroke:#CC0000,color:#660000,font-weight:bold,font-size:12px
    classDef node fill:#F0F0F0,stroke:#666666,stroke-width:2px,color:#000000,font-weight:bold

    subgraph Problem["THE PROBLEM"]
        class Problem problem
        style Problem fill:#FFE6E6,stroke:#CC0000,stroke-width:2.5px,color:#660000,padding:10px

        P1["Non-Linear Proxy&lt;br/&gt;Variables"]:::node --&gt;|"Leads to"| P2["Wrong Coefficient&lt;br/&gt;Signs &amp; Magnitudes"]:::node
        P3["High R² + Significant&lt;br/&gt;p-values"]:::node --&gt;|"Creates illusion of"| P4["Valid Results"]:::node
        P2 --&gt; P5["Misleading Policy&lt;br/&gt;Recommendations"]:::node
        P4 --&gt; P5
    end
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div><div class="column" style="width:4%;">

</div><div class="column" style="width:48%;">
<div class="cell" data-layout-align="default">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode default code-with-copy"><code class="sourceCode default"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>flowchart TD</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>    classDef solution fill:#E6F7E6,stroke:#00AA00,color:#003300,font-weight:bold,font-size:12px</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    classDef node fill:#F0F0F0,stroke:#666666,stroke-width:2px,color:#000000,font-weight:bold</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    subgraph Solution["THE SOLUTION"]</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>        class Solution solution</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>        style Solution fill:#E6F7E6,stroke:#00AA00,stroke-width:2.5px,color:#003300,padding:10px</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>        S1["Visual Diagnostics&lt;br/&gt;&amp; Graphical Analysis"]:::node --&gt;|"Identify"| S2["Statistical&lt;br/&gt;Regimes"]:::node</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>        S2 --&gt;|"Analyze"| S3["Linear Subsets&lt;br/&gt;of Data"]:::node</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>        S3 --&gt;|"Recover"| S4["Correct Coefficients&lt;br/&gt;&amp; Causal Estimates"]:::node</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>        S1 --&gt;|"Check for"| S5["Non-Linearity&lt;br/&gt;Patterns"]:::node</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>        S5 --&gt; S2</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>    end</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
    classDef solution fill:#E6F7E6,stroke:#00AA00,color:#003300,font-weight:bold,font-size:12px
    classDef node fill:#F0F0F0,stroke:#666666,stroke-width:2px,color:#000000,font-weight:bold

    subgraph Solution["THE SOLUTION"]
        class Solution solution
        style Solution fill:#E6F7E6,stroke:#00AA00,stroke-width:2.5px,color:#003300,padding:10px

        S1["Visual Diagnostics&lt;br/&gt;&amp; Graphical Analysis"]:::node --&gt;|"Identify"| S2["Statistical&lt;br/&gt;Regimes"]:::node
        S2 --&gt;|"Analyze"| S3["Linear Subsets&lt;br/&gt;of Data"]:::node
        S3 --&gt;|"Recover"| S4["Correct Coefficients&lt;br/&gt;&amp; Causal Estimates"]:::node
        S1 --&gt;|"Check for"| S5["Non-Linearity&lt;br/&gt;Patterns"]:::node
        S5 --&gt; S2
    end
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="final-assessment" class="level3">
<h3 class="anchored" data-anchor-id="final-assessment"><span style="color:brown; font-style:italic;">Final Assessment</span></h3>
<p><strong>Linear regression assumes linearity. When that assumption is violated—even slightly—the results can be catastrophically wrong.</strong> Our analysis demonstrates that regression models can produce results that are simultaneously statistically significant, well-fitting, and fundamentally incorrect when proxy variables exhibit non-linear relationships with the outcome.</p>
<p>The solution requires prioritizing graphical diagnostics, regime analysis, and theoretical coherence over blind reliance on statistical significance and R-squared values. <strong>Always question your models, visualize your data, and be skeptical of results that seem too good to be true—because they often are.</strong></p>
<!-- ::: {.callout-tip}
## 🎯 For 100% Grade: Focus on What's Most Interesting

**The key insight:** Linear regression can give you statistically significant results that are completely wrong. The challenge is understanding when and why this happens.

**What to investigate:**

- **Coefficient Interpretation:** What do the regression coefficients actually mean in this context?
- **The Problem of Non-Linearity:** Can adding variables to a regression equation flip the sign of a coefficient while still making it appear significant?

**Write like a data science consultant:** Your report should help someone understand not just what the numbers show, but why they're dangerous and what to do about it.
:::

## Technical Implementation Preferences 💡

### Setting Up Your Analysis

- Use `pandas` for data manipulation
- Use `matplotlib` and `seaborn` for visualizations
- Use `sklearn.linear_model` for regression analysis
- Use `statsmodels` for detailed regression output

### Visualization Preferences

- **Professional Styling:** Use consistent colors, clear labels, readable fonts, and informative titles

## Submission Checklist ✅

**Minimum Requirements (Required for Any Points):**

- [ ] Forked starter repository from [https://github.com/flyaflya/regressionChallenge.git](https://github.com/flyaflya/regressionChallenge.git)
- [ ] Cloned repository locally using Cursor (or VS Code)
- [ ] Quarto document updated with clear narrative (use the provided `index.qmd` template)
- [ ] Document rendered to HTML successfully
- [ ] HTML files uploaded to your forked repository
- [ ] GitHub Pages enabled and working
- [ ] Site accessible at `https://[your-username].github.io/regressionChallenge/`

**75% Grade Requirements:**

- [ ] Bivariate regression analysis with StressSurvey and coefficient interpretation (Question 1)
- [ ] Scatter plot with regression line for StressSurvey and interpretation (Question 2)
- [ ] Bivariate regression analysis with Time and coefficient interpretation (Question 3)
- [ ] Scatter plot with regression line for Time and interpretation (Question 4)
- [ ] Multiple regression analysis with StressSurvey and Time and coefficient comparison (Question 5)

**85% Grade Requirements:**

- [ ] Multiple regression analysis with Stress and Time (Question 6)
- [ ] Model comparison analysis between StressSurvey and Stress models (Question 7)

**95% Grade Requirements:**

- [ ] Real-world implications and headline analysis (Question 8)

**100% Grade Requirements:**

- [ ] Subset analysis to avoid misleading statistical significance (Question 9)

**Code Quality (All Grades):**

- [ ] Clean, well-commented code
- [ ] Appropriate use of regression functions
- [ ] Professional visualization styling
- [ ] Reproducible results

**Report Quality (Critical for Higher Grades):**

- [ ] Report structured as question and answer format (each question clearly stated, followed by answer)
- [ ] All challenge instructions, setup guides, and grading rubrics removed from final HTML
- [ ] Final report contains only Q&A responses, code outputs, and visualizations
- [ ] Clear, engaging narrative that tells a story
- [ ] Focus on the most interesting findings about regression interpretability
- [ ] Professional writing style (no AI-generated fluff)
- [ ] Concise analysis that gets to the point
- [ ] Practical insights that would help a real data scientist
- [ ] Visualizations that support your narrative, not overwhelm it

### Resources

- **Quarto Markdown:** [quarto.org/docs/authoring/markdown-basics.html](https://quarto.org/docs/authoring/markdown-basics.html)
- **Quarto Documentation:** [quarto.org/docs](https://quarto.org/docs)
- **Python Data Science Handbook:** [jakevdp.github.io/PythonDataScienceHandbook](https://jakevdp.github.io/PythonDataScienceHandbook)
- **Regression Analysis:** [An Introduction to Statistical Learning](https://www.statlearning.com/) 

## Essential Regression Concepts 🎯 {#sec-regression-concepts}

Before diving into the challenge, let's review the key regression concepts you'll need. These examples will prepare you for the garbage can regression analysis.

### 1. Simple Linear Regression: The Basics

Let's start with a basic linear regression to understand the mechanics:

::: {#cell-simple-regression-python .cell execution_count=13}
``` {.python .cell-code}
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

# Set seed for reproducibility
np.random.seed(123)

# Create simple example data
n = 50
x = np.random.normal(10, 3, n)
y = 2 * x + 3 + np.random.normal(0, 2, n)

# Fit linear regression
model = LinearRegression()
model.fit(x.reshape(-1, 1), y)

# Display results
print(f"Coefficient: {model.coef_[0]:.3f}")
print(f"Intercept: {model.intercept_:.3f}")
print(f"R-squared: {r2_score(y, model.predict(x.reshape(-1, 1))):.3f}")

# Create scatter plot with regression line
fig, ax = plt.subplots(figsize=(7, 4))
ax.scatter(x, y, alpha=0.7)
ax.plot(x, model.predict(x.reshape(-1, 1)), color='red', linewidth=2)
ax.set_title('Simple Linear Regression')
ax.set_xlabel('X Variable')
ax.set_ylabel('Y Variable')
ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()
```

::: {.cell-output .cell-output-stdout}
```
Coefficient: 1.949
Intercept: 3.592
R-squared: 0.915
```
:::

::: {.cell-output .cell-output-display}
![Python simple linear regression example](index_files/figure-html/simple-regression-python-output-2.png){#simple-regression-python width=663 height=374}
:::
:::


### 2. Multiple Regression: Adding Complexity

Now let's see how multiple variables interact:

::: {#cell-multiple-regression-python .cell execution_count=14}
``` {.python .cell-code}
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

# Set seed for reproducibility
np.random.seed(456)

# Create multiple regression example
n = 50
x1 = np.random.normal(10, 3, n)
x2 = np.random.normal(5, 2, n)
y = 2 * x1 + 0.5 * x2 + 3 + np.random.normal(0, 2, n)

# Fit multiple regression
X = np.column_stack([x1, x2])
model_multi = LinearRegression()
model_multi.fit(X, y)

# Display results
print(f"Coefficients: {model_multi.coef_}")
print(f"Intercept: {model_multi.intercept_:.3f}")
print(f"R-squared: {r2_score(y, model_multi.predict(X)):.3f}")

# Create pairs plot
data_df = pd.DataFrame({'x1': x1, 'x2': x2, 'y': y})
sns.pairplot(data_df)
plt.suptitle('Pairs Plot: Multiple Regression Variables', y=1.02)
plt.tight_layout()
plt.show()
```

::: {.cell-output .cell-output-stdout}
```
Coefficients: [1.96423174 0.216209  ]
Intercept: 4.969
R-squared: 0.867
```
:::

::: {.cell-output .cell-output-display}
![Python multiple regression example](index_files/figure-html/multiple-regression-python-output-2.png){#multiple-regression-python width=710 height=739}
:::
:::


::: {.callout-note}
## Statistical Significance at 5% Level

A coefficient is **statistically significant** when its p-value is less than 0.05.

- **p < 0.05**: Statistically significant
- **p ≥ 0.05**: Not statistically significant

### Understanding Scientific Notation in P-values

Sometimes you'll see p-values written in scientific notation like `7.89e-4`. Don't panic! This is just a way to write very small numbers:

- **7.89e-4** means 7.89 × 10⁻⁴ = 0.000789
- **2.34e-6** means 2.34 × 10⁻⁶ = 0.00000234
- **1.23e-2** means 1.23 × 10⁻² = 0.0123

**The key rule:** If you see "e-" in a p-value, it's always a very small number (less than 1). The number after "e-" tells you how many zeros come before the first non-zero digit.

**Examples:**
- 7.89e-4 = 0.000789 (less than 0.05, so significant!)
- 2.34e-6 = 0.00000234 (way less than 0.05, so very significant!)
- 1.23e-2 = 0.0123 (less than 0.05, so significant!)

**Remember:** Statistical significance doesn't mean the effect is large or important - it just means we're confident the effect isn't zero.
:::

## The Problem of Non-Linearity: A Deeper Look

The "garbage can regression" problem occurs when we include variables in our regression models that create misleading results, even when they appear statistically significant. This happens in several ways:

1. **Random correlations:** Even random variables can appear correlated by chance
2. **Overfitting:** More variables can improve fit without improving understanding
3. **Multiple testing:** The more variables we test, the more likely we are to find spurious relationships
4. **Non-linear relationships:** Variables with U-shaped, exponential, or other non-linear relationships with the outcome are forced into a linear framework, creating misleading coefficients

### Why This Matters

In the real world, non-linear relationships can lead to:

- **False policy recommendations:** Basing decisions on spurious correlations or false causal relationships
- **Wasted resources:** Pursuing interventions that don't actually work
- **Loss of credibility:** When results can't be replicated or don't make sense
- **Ethical issues:** Making decisions that affect people's lives based on bad science

### The Solution

The key is to always ask:

1. **Does this make theoretical sense?** Is there a plausible mechanism?
2. **Is the relationship robust?** Does it hold across different samples and specifications?
3. **Are we overfitting?** Do we have enough data relative to the number of variables?
4. **Can we interpret the coefficients?** Do the results tell a coherent story?
5. **Is the relationship truly linear?** Check for non-linear patterns that linear regression can't capture
6. **Are we forcing the wrong functional form?** Consider if polynomial terms, interactions, or transformations are needed
7. **Split the sample into meaningful subsets:** Analyze different "statistical regimes" to see if relationships hold consistently across different parts of your data
8. **Use graphical diagnostics:** Don't rely blindly on "canned" regressions—visualize the relationships to understand what's really happening

Remember: **Correlation is not causation, and regression coefficients can lie!** 📊 -->
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>